name: Daily Commit

on:
  schedule:
    - cron: '5 10 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 24f1002341@ds.study.iitm.ac.in
        run: echo "Running daily job"

      - name: Create commit
        run: |
          echo "Last run: $(date)" >> log.txt
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "Daily auto commit" || echo "No changes"
          git push
